server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_authority?serverTimezone=GMT%2B8
    username: root
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.juzi.security
  mapper-locations: classpath*:/mapper/*.xml

auth:
  rsa:
    pubKeyFile: D:\auth_key\rsa_key.pub
    priKeyFile: D:\auth_key\rsa_pri_key

